### ISSUE TITLE
진행 중 오류(/v1/member)-post

### ISSUE THREAD

**Issue by TopazKang** [2023-Capston-Design/Backend-RE#13]
email, date-time, departmentId validation 오류가 납니다요

**Comment by J-hoplin1** [comment]
- 기존에 Validation이 작동되지 않던 문제를 해결했습니다. main.ts에서 ValidationPipe 활성화를 해주지 않았던 문제입니다.
- Member 가입시 Plain JS Date() 객체가아닌 `YYYY-MM-DD` 타입으로 포맷을 픽스하도록 하겠습니다.
