### ISSUE TITLE
학번 중복확인 api 오류/v1/member/gid/{gid} -- (get)

### ISSUE THREAD

**Issue by TopazKang** [2023-Capston-Design/Backend-RE#14]
groupId 중복 확인 api가 어떤 값을 넣든 status=401 Unauthorized를 반환하는데, 확인 부탁드립니다.
![image](https://github.com/2023-Capston-Design/Backend-RE/assets/43803863/690bd982-754a-4682-9efa-8a608197d237)

**Comment by TopazKang** [comment]
확인해보니 groupId를 통한 회원정보 조회와 중복확인 api의 주소가 동일하여 권한이 없다는 오류가 뜨는것 같습니다.  확인 부탁드려요.

![image](https://github.com/2023-Capston-Design/Backend-RE/assets/43803863/5214d84e-105f-40b2-a445-36b67cec60db)

**Comment by J-hoplin1** [comment]
<img width="1144" alt="image" src="https://github.com/2023-Capston-Design/Backend-RE/assets/45956041/cd02732b-ad25-4516-b7cc-35ca3d204460">
API 엔드포인트 중복성이 있어서 하나의 API로 단편화했습니다. URL Parameter중 type은 Swagger에 있듯이 'email' 혹은 'gid'로 해주면 됩니다. 

```typescript
// member.enum.ts
export enum CheckType {
  EMAIL = 'email',
  GID = 'gid',
}

const checkTypeToArr = Object.keys(CheckType).map((x) => {
  return CheckType[x];
});

@Injectable()
export class CheckTypeValidationPipe implements PipeTransform {
  transform(value: any, metadata: ArgumentMetadata) {
    if (!checkTypeToArr.includes(value)) {
      throw new UnsupportedCheckType();
    }
    return value;
  }
}

// member.controller.ts
@Get('/check/:type/:value')
  @ApiOperation({
    summary: '회원 정보값의 중복값이 있는지 확인합니다',
    description: "type의 값은 'email' 혹은 'gid'가 되어야 합니다.",
  })
  @ApiOkResponse({ type: CommonResponseDto })
  @ApiBadRequestResponse({
    description: MEMBER_EXCEPTION_MSG.UnsupportedCheckType,
  })
  public async checkValueIsAvailable(
    @Param('type', CheckTypeValidationPipe) tp: CheckType
```

enum 기반으로 CheckType을 Validation하며, Request Handler단에서 PIpe를 통해서 검증을 진행합니다.

아직 Merge 이전이며 Merge시 추가 Comment 남기겠습니다.
