### ISSUE TITLE
(GET) /v1/class/available/{id} 학생 수강신청 가능한 강의 목록 조회 관련 문의입니다.

### ISSUE THREAD

**Issue by TopazKang** [2023-Capston-Design/Backend-RE#29]
수강신청 화면에서 필요한 강의 조회 api에도 instructor 정보가 같이 조회되게끔 수정해주실수 있을까요? 
![image](https://github.com/2023-Capston-Design/Backend-RE/assets/43803863/32580b2a-316a-4649-a3e0-ea9988b29595)
현재는 이런식으로 전달이 됩니다!

**Comment by J-hoplin1** [comment]
확인
